# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso pipeline
name: 'Execução manual - N1 - Trabalho final de pós-graduação'

# regras de disparo
# gatilho de execução manual = workflow_dispatch
on:
  workflow_dispatch:

# tarefas dentro do pipeline = jobs
jobs:
  trabalho-final-tests:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação do mocha
      - name: Instalando mocha
        run: npm install --save-dev mocha

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # executar os testes
      - name: Executando testes do trabalho final
        run: yarn run tests
        # run: npm test .\tests\trabalho-final.js